In [2]:
import numpy as np
from astropy.table import Table
import MB21_in
import logg_SB
import MB21
import MC_logg_Teff

In [3]:
def vmicro_mash(teff, logg, feh):
    return 0.14 - (0.08 * feh) + (4.90 * teff/1.0e4) - (0.47 * logg)

In [4]:
vmicro_mash(4500.2, 1.87, -2.5)

1.6661979999999998

In [14]:
# data = Table.read('new_EDR3_dist_green.csv', format='ascii', delimiter=',') 
data = np.genfromtxt('stellar_param_table.txt', names=True, dtype=None, encoding=None)
print(data)
# star_names = data['name'][np.in1d(data['name'],['cra2_gdr32672', 'cra2_gdr36912'])]
sgraqu_list = ['sgr2_gdr35584','sgr2_gdr32656','sgr2_gdr39936','aqu2_gdr33776','aqu2_gdr31472']
star_names = data['name'][np.in1d(data['name'],sgraqu_list)]
#name=np.array(all_gaia['name'])
# data = data[np.in1d(data['name'],['cra2_gdr32672', 'cra2_gdr36912'])]
data = data[np.in1d(data['name'],star_names)]
ra=data['ra']
dec=data['dec']
ebv=data['ebv']

av=3.1*ebv

ag=av*0.85926
abp=av*1.06794
arp=av*0.65199

met= (-1.9)*np.ones(len(ra))
# met = np.array([-2.8, -2.6, -0.3])
# met = np.array([-2.14, -1.75])
dist=data['dist']
dist_err=data['dist_err']
dist_err = dist/10.
# dist[0] /= 1000
# dist_err[0] /= 1000
G=data['phot_g_mean_mag']
C=data['bp_rp'] - (abp - arp) # bp-rp

[('hd122563', 210.63269043,   9.68609619, 0.0213, 318. , 4. ,  5.87496 , 1.218804 )
 ('ret2_mem',  54.03236729, -54.04320255, 0.0155,  30.2, 3. , 16.900171, 1.065945 )
 ('ret2_cand',  54.11534189, -53.97395817, 0.0148,  30.2, 3. , 16.413347, 1.317541 )
 ('cra2_gdr32672', 176.99663812, -18.17796387, 0.0305, 117.5, 1.1, 17.396591, 1.514427 )
 ('cra2_gdr36912', 177.53613367, -18.30407348, 0.0269, 117.5, 1.1, 17.438469, 1.426128 )
 ('sgr2_gdr35584', 298.16237992, -22.077479  , 0.0945,  73.1, 1. , 16.96482 , 1.4810028)
 ('sgr2_gdr32656', 298.18147542, -22.07734845, 0.0936,  73.1, 1. , 18.409101, 1.1939106)
 ('sgr2_gdr39936', 298.15343529, -22.04959484, 0.0954,  73.1, 1. , 17.308119, 1.3915062)
 ('aqu2_gdr33776', 338.53523191,  -9.32779807, 0.0561, 107.6, 3.6, 18.78467 , 1.4043884)
 ('aqu2_gdr31472', 338.46956478,  -9.28585488, 0.0575, 107.6, 3.6, 18.78599 , 1.1961269)]


In [15]:
Teff_mb,Teff_mb_err = MB21_in.MB21_in(C,met,100)
print(Teff_mb)

logg_sb,logg_sb_err=logg_SB.logg_SB(Teff_mb,Teff_mb_err,dist,dist_err,G,ag,1000)
print(logg_sb)

[[4362.6061285 ]
 [4902.3245401 ]
 [4515.42925847]
 [4404.90102286]
 [4797.87366523]]
[[0.79997949]
 [1.66904706]
 [1.02790951]
 [1.26162441]
 [1.47044813]]


In [16]:
 Teff_it,logg_it,Teff_err_it,logg_err_it = MC_logg_Teff.MC_logg_Teff(C,met,logg_sb,logg_sb_err, dist, dist_err,G,ag,1000)

Elapsed time: 24 s
Teff_final:
[4446.77821065] ± [81.09968864]
[4942.19492001] ± [97.60531811]
[4593.47497178] ± [89.08917258]
[4478.76685007] ± [76.84099979]
[4834.65158807] ± [95.40923338]
logg_final: 
[0.85393401] ± [0.10973571]
[1.69531617] ± [0.10274088]
[1.07251815] ± [0.11662837]
[1.29323844] ± [0.11063147]
[1.49257435] ± [0.11336979]


In [17]:
print(Teff_it, logg_it)
print(met)

[[4446.77821065]
 [4942.19492001]
 [4593.47497178]
 [4478.76685007]
 [4834.65158807]] [[0.85393401]
 [1.69531617]
 [1.07251815]
 [1.29323844]
 [1.49257435]]
[-1.9 -1.9 -1.9 -1.9 -1.9]


In [18]:
print(star_names, Teff_it[:,0], Teff_err_it[:,0], logg_it[:,0], logg_err_it[:,0], met)

['sgr2_gdr35584' 'sgr2_gdr32656' 'sgr2_gdr39936' 'aqu2_gdr33776'
 'aqu2_gdr31472'] [4446.77821065 4942.19492001 4593.47497178 4478.76685007 4834.65158807] [81.09968864 97.60531811 89.08917258 76.84099979 95.40923338] [0.85393401 1.69531617 1.07251815 1.29323844 1.49257435] [0.10973571 0.10274088 0.11662837 0.11063147 0.11336979] [-1.9 -1.9 -1.9 -1.9 -1.9]


In [19]:
for star, teff, teff_err, logg, logg_err, mh in zip(star_names, Teff_it[:,0], Teff_err_it[:,0], logg_it[:,0], logg_err_it[:,0], met):
    vmicro = vmicro_mash(teff, logg, mh)
    dvm1 = np.abs(vmicro - vmicro_mash(teff+teff_err, logg, mh))
    dvm2 = np.abs(vmicro - vmicro_mash(teff-teff_err, logg, mh))
    dvm3 = np.abs(vmicro - vmicro_mash(teff, logg+logg_err, mh))
    dvm4 = np.abs(vmicro - vmicro_mash(teff, logg-logg_err, mh))

    vmicro_err = (dvm1+dvm2+dvm3+dvm4)/2.
    print(star, teff, teff_err, logg, logg_err, mh, vmicro, vmicro_err)

sgr2_gdr35584 4446.778210652624 81.09968864291127 0.8539340124452883 0.1097357051982054 -1.9 2.0695723373705004 0.09131462887818254
sgr2_gdr32656 4942.194920009351 97.60531811209903 1.6953161683157445 0.10274087967306529 -1.9 1.9168769116961821 0.09611481932126886
sgr2_gdr39936 4593.474971778975 89.08917257551852 1.0725181466419804 0.11662837116529284 -1.9 2.038719207249967 0.09846902900969146
aqu2_gdr33776 4478.7668500698965 76.84099978571743 1.2932384368441288 0.11063146934689318 -1.9 1.8787736912175093 0.0896488804880411
aqu2_gdr31472 4834.651588072096 95.40923338056808 1.4925743521059027 0.11336978588296588 -1.9 1.9594693326655532 0.1000343237214727


In [13]:
# with open('star_param_errors.txt', 'w') as file:
#     print('# star_name teff teff_err logg logg_err mh vmicro vmirco_err', file=file)
#     for star, teff, teff_err, logg, logg_err, mh in zip(star_names, Teff_it[:,0], Teff_err_it[:,0], logg_it[:,0], logg_err_it[:,0], met):
#         vmicro = vmicro_mash(teff, logg, mh)
#         dvm1 = np.abs(vmicro - vmicro_mash(teff+teff_err, logg, mh))
#         dvm2 = np.abs(vmicro - vmicro_mash(teff-teff_err, logg, mh))
#         dvm3 = np.abs(vmicro - vmicro_mash(teff, logg+logg_err, mh))
#         dvm4 = np.abs(vmicro - vmicro_mash(teff, logg-logg_err, mh))

#         vmicro_err = (dvm1+dvm2+dvm3+dvm4)/2.
#         print(f'{star} {teff:.1f} {teff_err:.1f} {logg:.2f} {logg_err:.2f} {mh:.3f} {vmicro:.2f} {vmicro_err:.2f}', file=file)
        
        